### ISSUE TITLE
App tracking works on app store release but not on source code release

### ISSUE THREAD

**Issue by EdGoodall01** [tananaev/traccar-client-ios#19]
Hi

Using the source code for iOS from the website, the location does not update. However, if I use the app store release, it does. Does anyone know why this is, or what I am doing wrong? I'm probably doing something wrong (more likely, I'm very tired!)

Thanks

**Comment by tananaev** [comment]
You can try to compile code from the latest tag:
https://github.com/tananaev/traccar-client-ios/releases/tag/v1.4

**Comment by EdGoodall01** [comment]
Tried using that code, still the issue occurs. It doesn't request access to the location if that helps? And in the status does not show any location failed or location sent...

**Comment by tananaev** [comment]
It is the code that I used to build App Store version, so I don't understand how it's possible that App Store version works and your one doesn't.

App requests location in the following line, so you can try to put breakpoint and see if you it gets there:
https://github.com/tananaev/traccar-client-ios/blob/master/TraccarClient/ViewController.m#L93

**Comment by EdGoodall01** [comment]
Taken a look, still no changes and the breakpoints aren't really revealing anything. Were there any frameworks you added or something like that? I'm quite confused here as obviously it is the app store code, but the location dialog doesn't appear at all asking if I would like to allow the app to use the location?

**Comment by tananaev** [comment]
I think it won't appear if you disable locations in the settings.

**Comment by EdGoodall01** [comment]
@tananaev tried with on and off, several devices and tried re-downloading code - definitely missing something on my end. Any suggestions as to things I could have missed myself?

**Comment by tananaev** [comment]
Not sure what can go wrong there. The app is pretty simple. Maybe better to ask on StackOverflow because I'm not an iOS guru.

**Comment by EdGoodall01** [comment]
Can you let me know what version of Xcode you were using incase the frameworks are different?

**Comment by tananaev** [comment]
I think I uses Xcode version 5. Don't remember minor version number.

**Comment by EdGoodall01** [comment]
@tananaev So glad you said that as that is what I suspected - I'll try with v5 and let you know as I think the location framework and syntax changed between 5 and 6 (or something like that...)

**Comment by EdGoodall01** [comment]
Compiling with Xcode 5.1.1 works and submits location.

**Comment by tananaev** [comment]
I guess I need to update something if I want to release a new version. Thanks.
