### ISSUE TITLE
send failed iOS 8.4.1 traccar client

### ISSUE THREAD

**Issue by newbie1001** [tananaev/traccar-client-ios#22]
Hi I tried default setting with 
server address: demo.traccar.org
server port : 5005
frequency: 5
I am seeing "send failed" in the client logs.

**Comment by tananaev** [comment]
Please change port to 5055. The protocol has changed.

**Comment by newbie1001** [comment]
It worked! Thanks a ton... Amazing work!

**Comment by tananaev** [comment]
If you are interested you can read more information about the latest release of the app here:

https://www.traccar.org/blog/traccar-client-2-0-for-ios/
