### ISSUE TITLE
iOS Battery Level always 0

### ISSUE THREAD

**Issue by bradleyuk** [tananaev/traccar-client-ios#31]
Hi

Not sure if this a defect or future proofed but the latest iOS client always seems to send batt=0 at the end of the query string. 

Is this a placeholder for when battery level is supported or is this a defect?

Also quick question - if i increase the interval will it save battery? or is the GPS always on (and therefore draining) and just transmits at the interval provided?

Thanks

And great app btw!

**Comment by tananaev** [comment]
Looks like I need to set `batteryMonitoringEnabled` property to `YES` to be able to read battery status.

**Comment by PoD-Stas** [comment]
Simple solution is:

`-(double) batteryLevel
{
    UIDevice *myDevice = [UIDevice currentDevice];
    [myDevice setBatteryMonitoringEnabled:YES];
    double batteryLeft = (float)[myDevice batteryLevel] * 100;
    return batteryLeft;
}`

**Comment by tananaev** [comment]
I will try to include in the next release.

**Comment by PoD-Stas** [comment]
I did like it in my branch. Work fine but mistake near +/- 5-10%

**Comment by w32gold** [comment]
Hi, used the latest Traccar-iOS codes but still getting the "zero battery". Any further ideas in fixing this? thanks.

**Comment by tananaev** [comment]
It means that your device doesn't provide this information.

**Comment by w32gold** [comment]
Sorry for my ignorance, but how do I make the iPhone/iPad provide such battery information.
I've seen it sending a battery percentage before. Thanks!

**Comment by tananaev** [comment]
The issue should be fixed now. We need to wait a bit till Apple approves the new version.
