### ISSUE TITLE
App outside the Apple Store

### ISSUE THREAD

**Issue by Turbovix** [tananaev/traccar-client-ios#41]
Hello,
Is there any way to get the app to install via Cydia? Because Apple will not let me install the Traccar on an Iphone 4, since the IOS of it is 7.xxx

**Comment by tananaev** [comment]
It has nothing to do with Apple. The app project is built with 8.0 as a target SDK, so it won't install on anything older.

You can try to build it yourself with lower SDK, but some things might not work or you might get some compilation issues.

**Comment by Turbovix** [comment]
Youtube was not available, however, I did install an old version through Cydia, and then the app was updated by the apple store itself.
Thank you.

**Comment by tananaev** [comment]
You can always get an older version tag from the repository and compile it yourself.

**Comment by Turbovix** [comment]
OK thank you!
It worked very well!
