### ISSUE TITLE
Issue with batteryLevel == 100. iOS 10x

### ISSUE THREAD

**Issue by SergeyBulyno** [tananaev/traccar-client-ios#43]
Hi, I use ZendeskSDK (1.7.4.1) and v(1.9.0.1)   
Method  [ZDKDeviceInfo deviceInfoDictionary] always return battery level == 100. 
I changed sdk version, initialization (via fabric and initializeWithAppId:zendeskUrl: clientId:), try launch [ZDKDeviceInfo  batteryLevel] directly, but nothing help me.

**Comment by tananaev** [comment]
How is your question related to Traccar Client?

**Comment by SergeyBulyno** [comment]
Oh, Sorry. Something happen wrong.
