### ISSUE TITLE
inappsettingskit/IASKappsettingviewcontroller.h file not found

### ISSUE THREAD

**Issue by vksdgreat** [tananaev/traccar-client-ios#45]
Hi,
I am new to IOS. I am trying to run client app in xcode but i am getting this error.
inappsettingskit/IASKappsettingviewcontroller.h file not found
In TCMainViewController.h file

 please give a solution

**Comment by tananaev** [comment]
You need to build Carthage dependencies.

**Comment by gsujathap** [comment]
@tananaev How can I build Carthage dependencies

**Comment by tananaev** [comment]
Run `carthage update --platform iOS`. If you have any further questions, I would recommend to Google first.
