### ISSUE TITLE
Idea for battery saving

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-client-ios#52]
Run low accuracy location updates, so update is not called every second. Then in callback request high accuracy location.

Suggested by Apple engineer.

**Comment by tananaev** [comment]
Implemented location accuracy option for now instead.

**Comment by LNFWebsite** [comment]
Hi, thanks for making such a useful GPS tracking service!

Traccar Client works great, except for the immense battery usage even at slow intervals on iOS.
I was curious as to when you'll be able to push this change to the App Store?

Thanks ahead.

**Comment by tananaev** [comment]
Probably in a couple of weeks time.

**Comment by LNFWebsite** [comment]
Okay, thanks for the quick response!

**Comment by LNFWebsite** [comment]
Any update as to the battery drain issue?

**Comment by tananaev** [comment]
The app has been released. What kind of updates are you looking for?

**Comment by LNFWebsite** [comment]
I'm sorry, I hadn't noticed that you updated the app...

I'll try it out again and let you know whether the battery drain is any better.

**Comment by tananaev** [comment]
Make sure you select medium or low accuracy.

**Comment by LNFWebsite** [comment]
Yes, the battery drain is much less! Thank you very much!
