### ISSUE TITLE
Service Automatically Stopped In IOS Client

### ISSUE THREAD

**Issue by vishalkalaria** [tananaev/traccar-client-ios#56]
Hi i have install latest IOS Version Of Traccar in my I PHONE 5s The Datat Are Sending Perfect But After  Idol For Few Minutes The Application Service Automatically Stooped So When I Restart Service Status It Will Work Again

I Want To Change That Every time  When Cellphone Has A Internet Connection And The Location Data Will Be Sent to the Server

And In Android Client Version New Version Not Working Properly In Some Few Model

**Comment by tananaev** [comment]
Closing as duplicate:

https://www.traccar.org/forums/topic/service-automatically-stopped-in-ios-client/

Please don't post your question in two places next time.
